version: "3.8"

volumes:
  esdata01:
    driver: local
  # esdata02:
  #   driver: local
  kibanadata:
    driver: local

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es01
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    ports:
      - ${ES_PORT}:9200
      # - 9300:9300
    networks:
      - elastic
  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
  #   container_name: es02
  #   volumes:
  #     - esdata02:/usr/share/elasticsearch/data
  #   environment:
  #     - "discovery.type=single-node"
  #     - ELASTIC_USERNAME=elastic
  #     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  #     - xpack.security.enabled=true
  #   ports:
  #     - ${ES_PORT}:9200
  #     - 9300:9300
  #   networks:
  #     - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS="http://es01:${ES_PORT}"
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=mnuuf6Ax2jRD7nSyB*5A
      - xpack.security.enabled=true
    links:
      - es01
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - elastic
    depends_on:
      - es01

networks:
  elastic:
    driver: bridge
